gcp:
  project_id: dtc-de-course-412710
  bucket: stackexchange-data
  dataset: stackexchange_data
  credentials_path: google_credentials.json

services:
  - datascience
  - ai
  - genai

init_url: https://archive.org/download/stackexchange/

start_date: 2024-04-14 00:00:00